import { Geist_Mono, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import TopBar from "./components/layout/TopBar";
import MessageInput from "./components/layout/MessageInput";
import SideBar from "./components/layout/SideBar";

const jakartaSans = Plus_Jakarta_Sans({
    variable: "--font-jakarta-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={`${jakartaSans.variable} ${geistMono.variable}`}>
                <div className='container'>
                    <SideBar />
                    <div className='content'>
                        <TopBar />
                        {children}
                        <MessageInput />
                    </div>
                </div>
            </body>
        </html>
    );
}
