export const messages = [
    {
        id: "15",
        userID: "1",
        avatar: "/images/avatars/mainAvatar.webp",
        online: false,
        isSystem: false,
        name: "Artificium",
        time: "11sec ago",
        text: "I'm glad you like the name Cosmic Voyager! And I agree, it's a great name for a spaceship. As for the concept art, I have some new designs that might be more to your liking. Take a look at these images.",
        actions: [
            {
                actionName: "Regenerate response",
                subActions: [],
            },
            {
                actionName: "Modify",
                subActions: [
                    {
                        id: "1",
                        subActionName: "Create variation",
                        subActionIcon: "/images/icons/magic-wand.svg",
                    },
                    {
                        id: "2",
                        subActionName: "Adjust",
                        subActionIcon: "/images/icons/sliders.svg",
                    },
                    {
                        id: "3",
                        subActionName: "Share",
                        subActionIcon: "/images/icons/link.svg",
                    },
                    {
                        id: "4",
                        subActionName: "Export",
                        subActionIcon: "/images/icons/download.svg",
                    },
                ],
            },
        ],
        options: [],
        tags: [],
        images: [
            "/images/chat/Image5.webp",
            "/images/chat/Image6.webp",
            "/images/chat/Image7.webp",
        ],
    },
    {
        id: "14",
        userID: "1",
        avatar: "/images/avatars/mainAvatar.webp",
        online: false,
        isSystem: false,
        name: "Artificium",
        time: "11sec ago",
        text: "loader",
        actions: [
            {
                actionName: "Pause generating",
                subActions: [],
            },
        ],
        options: [],
        tags: [],
        images: [],
    },
    {
        id: "13",
        userID: "",
        avatar: "",
        online: true,
        isSystem: false,
        isSystem: true,
        name: "",
        time: "",
        text: "Tip: From now Artificium has memorized the name 'Cosmic Voyager' and added it to your project Library.",
        actions: [],
        options: [],
        tags: [],
        images: ["/images/icons/lamp-blue.svg"],
    },
    {
        id: "12",
        userID: "2",
        avatar: "/images/avatars/Avatar2.webp",
        online: true,
        isSystem: false,
        name: "Ryan Lee",
        time: "4sec ago",
        text: "Actually, I think I really like Cosmic Voyager. Maybe we could stick with that name and work on designing a more realistic concept art? 🤔",
        actions: [],
        options: [],
        tags: [],
        images: [],
    },
    {
        id: "11",
        userID: "1",
        avatar: "/images/avatars/mainAvatar.webp",
        online: false,
        isSystem: false,
        name: "Artificium",
        time: "11sec ago",
        text: "Sure thing! How about these spaceship names: Here are a few concept arts that also might inspire you. Take a look!",
        actions: [
            {
                actionName: "Regenerate response",
                subActions: [],
            },
            {
                actionName: "Modify",
                subActions: [
                    {
                        id: "1",
                        subActionName: "Create variation",
                        subActionIcon: "/images/icons/magic-wand.svg",
                    },
                    {
                        id: "2",
                        subActionName: "Adjust",
                        subActionIcon: "/images/icons/sliders.svg",
                    },
                    {
                        id: "3",
                        subActionName: "Share",
                        subActionIcon: "/images/icons/link.svg",
                    },
                    {
                        id: "4",
                        subActionName: "Export",
                        subActionIcon: "/images/icons/download.svg",
                    },
                ],
            },
        ],
        options: [],
        tags: ["Starfire", "Celestia", "Cosmic Voyager"],
        images: [
            "/images/chat/Image2.webp",
            "/images/chat/Image3.webp",
            "/images/chat/Image4.webp",
        ],
    },

    {
        id: "10",
        userID: "3",
        avatar: "/images/avatars/Avatar6.webp",
        online: true,
        isSystem: false,
        name: "Isabella Chen",
        time: "just now",
        text: "Good point! Let's see... How about these names: Do any of those spark some inspiration? Also, have you seen this concept art yet? It's absolutely stunning 🔥 🔥 🔥",
        actions: [],
        options: [],
        tags: ["Cosmic Voyager", "Galaxy Explorer", "Nova Pioneer"],
        images: ["/images/chat/Image1.webp"],
    },
    {
        id: "9",
        userID: "2",
        avatar: "/images/avatars/Avatar2.webp",
        online: true,
        isSystem: false,
        name: "Ryan Lee",
        time: "4sec ago",
        text: "Hmm, those are good. But I was hoping for something a bit more unique. Maybe a name that relates to the story in some way? What you think @issabel ?",
        actions: [],
        options: [],
        tags: [],
        images: [],
    },
    {
        id: "8",
        userID: "1",
        avatar: "/images/avatars/mainAvatar.webp",
        online: false,
        isSystem: false,
        name: "Artificium",
        time: "11sec ago",
        text: "How about exploring the backstory of the spaceship's name, Odyssey? Maybe it was named after the captain's daughter who always dreamed of exploring the stars. I have some ideas!",
        actions: [
            {
                actionName: "Regenerate response",
                subActions: [],
            },
            {
                actionName: "Modify",
                subActions: [
                    {
                        id: "1",
                        subActionName: "Create variation",
                        subActionIcon: "/images/icons/magic-wand.svg",
                    },
                    {
                        id: "2",
                        subActionName: "Adjust",
                        subActionIcon: "/images/icons/sliders.svg",
                    },
                    {
                        id: "3",
                        subActionName: "Share",
                        subActionIcon: "/images/icons/link.svg",
                    },
                    {
                        id: "4",
                        subActionName: "Export",
                        subActionIcon: "/images/icons/download.svg",
                    },
                ],
            },
        ],
        options: [],
        tags: ["🚀  Stellara", "🌟  Galaxia", "💫  Astraia"],
        images: [],
    },
    {
        id: "7",
        userID: "2",
        avatar: "/images/avatars/Avatar2.webp",
        online: true,
        isSystem: false,
        name: "Ryan Lee",
        time: "4sec ago",
        text: "I'm not sure, maybe something related to the spaceship?",
        actions: [],
        options: [],
        tags: [],
        images: [],
    },
    {
        id: "6",
        userID: "1",
        avatar: "/images/avatars/mainAvatar.webp",
        online: false,
        isSystem: false,
        name: "Artificium",
        time: "11sec ago",
        text: "Of course! What kind of ideas are you looking for?",
        actions: [
            {
                actionName: "Regenerate response",
                subActions: [],
            },
            {
                actionName: "Modify",
                subActions: [
                    {
                        id: "1",
                        subActionName: "Create variation",
                        subActionIcon: "/images/icons/magic-wand.svg",
                    },
                    {
                        id: "2",
                        subActionName: "Adjust",
                        subActionIcon: "/images/icons/sliders.svg",
                    },
                    {
                        id: "3",
                        subActionName: "Share",
                        subActionIcon: "/images/icons/link.svg",
                    },
                    {
                        id: "4",
                        subActionName: "Export",
                        subActionIcon: "/images/icons/download.svg",
                    },
                ],
            },
        ],
        options: [],
        tags: [],
        images: [],
    },
    {
        id: "5",
        userID: "2",
        avatar: "/images/avatars/Avatar2.webp",
        online: false,
        isSystem: false,
        name: "Ryan Lee",
        time: "13sec ago",
        text: "Hi, can you help me with some ideas for the show?",
        actions: [],
        options: [],
        tags: [],
        images: [],
    },
    {
        id: "4",
        userID: "1",
        avatar: "/images/avatars/mainAvatar.webp",
        online: false,
        isSystem: false,
        name: "Artificium",
        time: "11sec ago",
        text: "Okay, let's explore some options related to the spaceship. Here are some things I can do for you:",
        actions: [
            {
                actionName: "Regenerate response",
                subActions: [],
            },
            {
                actionName: "Modify",
                subActions: [
                    {
                        id: "1",
                        subActionName: "Create variation",
                        subActionIcon: "/images/icons/magic-wand.svg",
                    },
                    {
                        id: "2",
                        subActionName: "Adjust",
                        subActionIcon: "/images/icons/sliders.svg",
                    },
                    {
                        id: "3",
                        subActionName: "Share",
                        subActionIcon: "/images/icons/link.svg",
                    },
                    {
                        id: "4",
                        subActionName: "Export",
                        subActionIcon: "/images/icons/download.svg",
                    },
                ],
            },
        ],
        options: [
            {
                optionName: "Image generation",
                optionIcon: "/images/icons/image.svg",
                link: "",
            },
            {
                optionName: "Code engineering",
                optionIcon: "/images/icons/code.svg",
                link: "",
            },

            {
                optionName: "Content creation",
                optionIcon: "/images/icons/pencil.svg",
                link: "",
            },
            {
                optionName: "Idea generation",
                optionIcon: "/images/icons/bulb.svg",
                link: "",
            },
        ],
        tags: [],
        images: [],
    },
    {
        id: "3",
        userID: "2",
        avatar: "/images/avatars/Avatar2.webp",
        online: true,
        isSystem: false,
        name: "Ryan Lee",
        time: "4sec ago",
        text: "I'm not sure, maybe something related to the spaceship?",
        actions: [],
        options: [],
        tags: [],
        images: [],
    },
    {
        id: "2",
        userID: "1",
        avatar: "/images/avatars/mainAvatar.webp",
        online: false,
        isSystem: false,
        name: "Artificium",
        time: "11sec ago",
        text: "Of course! What kind of ideas are you looking for?",
        actions: [
            {
                actionName: "Regenerate response",
                subActions: [],
            },
            {
                actionName: "Modify",
                subActions: [
                    {
                        id: "1",
                        subActionName: "Create variation",
                        subActionIcon: "/images/icons/magic-wand.svg",
                    },
                    {
                        id: "2",
                        subActionName: "Adjust",
                        subActionIcon: "/images/icons/sliders.svg",
                    },
                    {
                        id: "3",
                        subActionName: "Share",
                        subActionIcon: "/images/icons/link.svg",
                    },
                    {
                        id: "4",
                        subActionName: "Export",
                        subActionIcon: "/images/icons/download.svg",
                    },
                ],
            },
        ],
        options: [],
        tags: [],
        images: [],
    },
    {
        id: "1",
        userID: "2",
        avatar: "/images/avatars/Avatar2.webp",
        online: false,
        isSystem: false,
        name: "Ryan Lee",
        time: "13sec ago",
        text: "Hi, can you help me with some ideas for the show?",
        actions: [],
        options: [],
        tags: [],
        images: [],
    },
];
