export const messages = [
    {
        id: "6",
        userID: "1",
        avatar: "/images/avatars/DavidSingh.png",
        online: false,
        isSystem: false,
        name: "David Singh 👹",
        time: "2 min ago",
        text: "How about someone with a military background? They would have experience leading a team in high-pressure situations.",
        answers: [
            {
                id: "7",
                userID: "1",
                avatar: "/images/avatars/AdamGreen.png",
                online: true,
                isSystem: false,
                name: "Adam Green",
                time: "just now",
                text: "Good point, David. I was also thinking that maybe this leader character could have a personal stake in the mission, like they have a family member or loved one back on Earth that they're trying to protect. It could add some emotional depth to the character.",
                answers: [],
                actions: [],
                options: [],
                tags: [],
                images: [],
            },
        ],
        actions: [],
        options: [],
        tags: [],
        images: [],
    },
    {
        id: "5",
        userID: "1",
        avatar: "/images/avatars/mainAvatar.webp",
        online: false,
        isSystem: false,
        name: "Artificium",
        time: "just now",
        text: "Of course, I'd be happy to help. How about a character named Captain Drake? He's a natural born leader with years of experience in space exploration. Here are a few concept arts that might help bring him to life.",
        answers: [],
        actions: [
            {
                actionName: "Regenerate response",
                subActions: [],
            },
            {
                actionName: "Modify",
                subActions: [
                    {
                        id: "1",
                        subActionName: "Create variation",
                        subActionIcon: "/images/icons/magic-wand.svg",
                    },
                    {
                        id: "2",
                        subActionName: "Adjust",
                        subActionIcon: "/images/icons/sliders.svg",
                    },
                    {
                        id: "3",
                        subActionName: "Share",
                        subActionIcon: "/images/icons/link.svg",
                    },
                    {
                        id: "4",
                        subActionName: "Export",
                        subActionIcon: "/images/icons/download.svg",
                    },
                ],
            },
        ],
        options: [],
        tags: [],
        images: [
            "/images/chat/Image8.png",
            "/images/chat/Image9.png",
            "/images/chat/Image10.png",
        ],
    },
    {
        id: "4",
        userID: "2",
        avatar: "/images/avatars/EmilyLiu.png",
        online: true,
        isSystem: false,
        isDay: false,
        name: "Emily Liu",
        time: "5 sec ado",
        text: "Well, we definitely need a strong leader character who can command the crew and make tough decisions. @Artificium, can you help?",
        answers: [],
        actions: [],
        options: [],
        tags: [],
        images: [],
    },
    {
        id: "3",
        userID: "2",
        avatar: "/images/avatars/AdamGreen.png",
        online: true,
        isSystem: false,
        isDay: false,
        name: "Adam Green",
        time: "5 min ado",
        text: "Hey guys, I was thinking about some character ideas for our show. What do you think we should focus on?",
        answers: [],
        actions: [],
        options: [],
        tags: [],
        images: [],
    },
    {
        id: "2",
        userID: "",
        avatar: "",
        online: false,
        isSystem: false,
        isDay: true,
        name: "",
        time: "",
        text: "Today",
        answers: [],
        actions: [],
        options: [],
        tags: [],
        images: [],
    },
    {
        id: "1",
        userID: "2",
        avatar: "/images/avatars/LilyPatel.png",
        online: false,
        isSystem: false,
        isDay: false,
        name: "Lily Patel 💅🏻",
        time: "27.04.2023, 13:30",
        text: "Agreed. In the meantime, let's keep pushing forward with this episode. I think it's going to be a real crowd-pleaser.",
        answers: [],
        actions: [
            {
                actionName: "Reply",
                subActions: [],
            },
            {
                actionName: "🔥",
                subActions: [],
            },
            {
                actionName: "💅🏻",
                subActions: [],
            },
            {
                actionName: "🙄",
                subActions: [],
            },
        ],
        options: [],
        tags: [],
        images: [],
    },
];
