export const LibraryItems = [
    {
        id: "10",
        category: "Ideas",
        title: "Potential partnerships or collaborations with other artists or creators.",
        text: "",
        users: [],
        comments: "0",
        tags: [],
        images: [],
    },
    {
        id: "9",
        category: "Ideas",
        title: "Ideas for potential spin-offs or other related media.",
        text: "",
        users: [],
        comments: "0",
        tags: [],
        images: [],
    },
    {
        id: "8",
        category: "Ideas",
        title: "A list of potential plot points or story arcs.",
        text: "",
        users: [],
        comments: "0",
        tags: [],
        images: [],
    },
    {
        id: "7",
        category: "Ideas",
        title: "Concept art for potential new characters or locations.",
        text: "",
        users: [],
        comments: "0",
        tags: [],
        images: [],
    },
    {
        id: "6",
        category: "Documents",
        title: "Dialogue snippets",
        text: "2 documents, 10384 words",
        users: [],
        comments: "0",
        tags: [],
        images: [],
    },
    {
        id: "5",
        category: "Documents",
        title: "Scene descriptions",
        text: "5 documents, 23992 words",
        users: [],
        comments: "0",
        tags: [],
        images: [],
    },
    {
        id: "4",
        category: "Documents",
        title: "Plot outline",
        text: "1 document, 18745 words",
        users: [],
        comments: "0",
        tags: [],
        images: [],
    },
    {
        id: "3",
        category: "Documents",
        title: "Character bios",
        text: "3 documents, 43832 words",
        users: [],
        comments: "0",
        tags: [],
        images: [],
    },
    {
        id: "2",
        category: "Images",
        title: "Cosmic Voyager",
        text: "Main spacecraft used by the crew in the story. It is a highly advanced vessel designed to withstand the harsh conditions of space and capable of traveling vast distances at incredible speeds.",
        users: [],
        comments: "27",
        tags: [],
        images: [
            "/images/chat/Image5.webp",
            "/images/chat/Image6.webp",
            "/images/chat/Image7.webp",
        ],
    },
    {
        id: "1",
        category: "Images",
        title: "Captain Drake",
        text: "Natural born leader with years of experience in space exploration.",
        users: [],
        comments: "12",
        tags: [],
        images: [
            "/images/chat/Image5.webp",
            "/images/chat/Image6.webp",
            "/images/chat/Image7.webp",
        ],
    },
];
